# Generated by Django 5.2 on 2025-07-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_publish_date_alter_post_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
